In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"d:\thony\used_cars_prediction\data\vehicles.csv")

In [4]:
features = [
    'year',
    'manufacturer',
    'odometer',
    'fuel',
    'transmission',
    'title_status',
    'type',
    'state'
]

target = 'price'

df_ml = df[features + [target]].copy()

print(df_ml.shape)
print(df_ml.isnull().sum())

(426880, 9)
year             1205
manufacturer    17646
odometer         4400
fuel             3013
transmission     2556
title_status     8242
type            92858
state               0
price               0
dtype: int64

In [5]:
df_ml[df_ml['price'] < 0]

Empty DataFrame
Columns: [year, manufacturer, odometer, fuel, transmission, title_status, type, state, price]
Index: []

In [6]:
important_columns = [
    'year',
    'manufacturer',
    'odometer',
    'price'
]

df_ml = df_ml.dropna(subset=important_columns)

In [7]:
print(df_ml.shape)
print(df_ml.isnull().sum())

(405077, 9)
year                0
manufacturer        0
odometer            0
fuel             2009
transmission     1624
title_status     7204
type            85533
state               0
price               0
dtype: int64

In [8]:
df_ml = df_ml[df_ml['price'] <= 57050]
df_ml = df_ml[df_ml['price'] > 500]

In [9]:
columns_to_fill = [
    'fuel',
    'transmission',
    'title_status',
    'type'
]

df_ml[columns_to_fill] = df_ml[columns_to_fill].fillna('unknown')

In [10]:
df_ml.groupby('manufacturer').size()

manufacturer
acura               5522
alfa-romeo           852
aston-martin          11
audi                6752
bmw                13110
buick               5063
cadillac            6283
chevrolet          47752
chrysler            5468
datsun                59
dodge              11433
ferrari                9
fiat                 730
ford               61347
gmc                14267
harley-davidson      136
honda              19260
hyundai             9041
infiniti            4391
jaguar              1861
jeep               16560
kia                 7255
land rover            11
lexus               7526
lincoln             3929
mazda               4901
mercedes-benz       9565
mercury             1078
mini                2211
mitsubishi          2997
morgan                 3
nissan             16667
pontiac             2188
porsche             1135
ram                15231
rover               1791
saturn              1055
subaru              8740
tesla                746
toyota             30510
volkswagen          8442
volvo               3186
dtype: int64

In [11]:
import numpy as np

df_ml['price'] = np.log1p(df_ml['price'])
df_ml['odometer'] = np.log1p(df_ml['odometer'])
year_centered = df_ml['year'] - df_ml['year'].mean()
df_ml['year_squared'] = year_centered ** 2
df_ml['odometer_squared'] = df_ml['odometer'] ** 2
df_ml['car_age'] = 2026 - df_ml['year']
df_ml['age_odometer_interaction'] = (
    df_ml['year'] * df_ml['odometer']
)

In [12]:
df_encoded = pd.get_dummies(df_ml, columns=['manufacturer', 'fuel', 'transmission', 'title_status', 'type', 'state'])
df_encoded.head()

,year,odometer,price,year_squared,odometer_squared,car_age,age_odometer_interaction,manufacturer_acura,manufacturer_alfa-romeo,manufacturer_aston-martin,...,state_sd,state_tn,state_tx,state_ut,state_va,state_vt,state_wa,state_wi,state_wv,state_wy
27,2014.0,10.966887,10.422013,8.024475,120.272612,12.0,22087.310590,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,2010.0,11.173669,10.025307,1.362472,124.850887,16.0,22459.075408,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,2020.0,9.860632,10.586357,78.017479,97.232068,6.0,19918.477129,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,2017.0,10.624371,10.341452,34.020977,112.877270,9.0,21429.357291,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,2013.0,11.759793,9.615872,3.358974,138.292740,13.0,23672.464024,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
import matplotlib.pyplot as plt

plt.boxplot(df_encoded["price"])

plt.ylabel("price")
plt.title("Boxplot des prix voitures")

plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
df_encoded.to_csv('data/vehicles_encoded.csv', index=False)