In [24]:
import pandas as pd

In [25]:
df = pd.read_csv(r"d:\thony\used_cars_prediction\data\vehicles.csv")

In [26]:
features = [
    'year',
    'manufacturer',
    'odometer',
    'fuel',
    'transmission',
    'title_status',
    'type',
    'state'
]

target = 'price'

df_ml = df[features + [target]].copy()

print(df_ml.shape)
print(df_ml.isnull().sum())

(426880, 9)
year             1205
manufacturer    17646
odometer         4400
fuel             3013
transmission     2556
title_status     8242
type            92858
state               0
price               0
dtype: int64

In [27]:
df_ml[df_ml['price'] < 0]

Empty DataFrame
Columns: [year, manufacturer, odometer, fuel, transmission, title_status, type, state, price]
Index: []

In [30]:
important_columns = [
    'year',
    'manufacturer',
    'odometer',
    'price'
]

df_ml = df_ml.dropna(subset=important_columns)

In [ ]:
print(df_ml.shape)
print(df_ml.isnull().sum())

(399504, 10)
year            0
manufacturer    0
model           0
odometer        0
fuel            0
transmission    0
title_status    0
type            0
state           0
price           0
dtype: int64

In [ ]:
df_ml = df_ml[df_ml['price'] <= 100000]

In [31]:
columns_to_fill = [
    'fuel',
    'transmission',
    'title_status',
    'type'
]

df_ml[columns_to_fill] = df_ml[columns_to_fill].fillna('unknown')

In [32]:
df_ml.dtypes

year            float64
manufacturer        str
odometer        float64
fuel                str
transmission        str
title_status        str
type                str
state               str
price             int64
dtype: object

In [33]:
df_encoded = pd.get_dummies(df_ml, columns=['manufacturer', 'fuel', 'transmission', 'title_status', 'type', 'state'])
df_encoded.head()

,year,odometer,price,manufacturer_acura,manufacturer_alfa-romeo,manufacturer_aston-martin,manufacturer_audi,manufacturer_bmw,manufacturer_buick,manufacturer_cadillac,...,state_sd,state_tn,state_tx,state_ut,state_va,state_vt,state_wa,state_wi,state_wv,state_wy
27,2014.0,57923.0,33590,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,2010.0,71229.0,22590,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,2020.0,19160.0,39590,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,2017.0,41124.0,30990,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,2013.0,128000.0,15000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False